### ISSUE TITLE
Piwik reporting missing parameters

### ISSUE THREAD

**Issue by emmajane** [humanitarianresponse/site#339] opened 2016-02-14 11:29 UTC
When I log into the site, I am redirected to a URL that returns the error:

Error: The parameter 'space_id' isn't set in the Request, and a default value wasn't provided.

![2016-02-14 at 11 14](https://cloud.githubusercontent.com/assets/1299320/13033423/ae809564-d30d-11e5-9e25-a302a78d644d.png)

BlackMesh has also been reporting issues from Piwik:

````
We have been getting intermittent alerts tonight for the following:
Service
HTTPS Content No. 4 -- stats.humanitarianresponse.info
On Host
568ellb01.blackmesh.com

We have not received any indication of a problem in any of the backend content
checks. Is your team actively working on the site, or would you like any
assistance in resolving the problem, please let us know.
Thanks.
````

**Comment by pcambra** [comment] 2016-02-15 09:19
This is a duplicate of #334.

The email reported has been answered already, it was related with the update and the geolocation issues.

**Closed by pcambra** 2016-02-15 09:19 UTC
Labels: analytics, bug, st - on deck
