### ISSUE TITLE
Pulling Assessments from UNHCR Data portal

### ISSUE THREAD

**Issue by javedyousafzai** [humanitarianresponse/site#98] opened 2015-09-16 09:47 UTC
UNHCR has assessments registry on their [Data Portal] (http://data.unhcr.org) which we could pull into HR.info operational websites using their API. This will require some investigation to integrate it.

**Comment by emmajane** [comment] 2015-12-03 11:27
Duplicate of #57. Closing this issue.

**Closed** 2015-12-03 11:29 UTC
Labels: enhancement, integration
