### ISSUE TITLE
Colombia site - Dynamic block - Date sorting issue 

### ISSUE THREAD

**Issue by javedyousafzai** [humanitarianresponse/site#109] opened 2015-09-25 10:00 UTC
[Colombia] (https://www.humanitarianresponse.info/en/operations/colombia) office is facing issues with the 'Latest Document' block and the last document "Informe de situación No. 8 - Colombia: " is not showing in the Latest document block. @MartinMaritim and I checked other sites and they all are fine, but only the Colombia site.

If I login and do the 'page customize', I see that the all the latest documents appear fine, but as anonymous user, I can't see what I am seeing in the screen-shot below.

@pcambra, I have asked @MartinMaritim for now but we need to find fix for it.

@humphreymburu! do you have any idea?

![image](https://cloud.githubusercontent.com/assets/3966785/10097820/46b10226-637c-11e5-8f81-718067dbcbb6.png)

**Comment by guillaumev** [comment] 2015-09-25 12:39
The issue is not between logged in or logged out, it's between the Spanish version and the English version:

* https://www.humanitarianresponse.info/en/operations/colombia (issue)
* https://www.humanitarianresponse.info/es/operations/colombia (no issue)

What's happening is that the document they want to appear first ("Informe de situacion No 8") has its language set to Spanish, so it appears first, but only on the Spanish version of the site. As a quick workaround, they can just translate the document to English and they should see it show up first on both the Spanish and English versions of the site.

As a longer term workaround, showing all documents regardless of the language they are in can be investigated.

**Comment by javedyousafzai** [comment] 2015-09-25 12:42
Many thanks @guillaumev , I will let @pcambra look into the longer term solution for this case.

**Comment by pcambra** [comment] 2015-09-28 09:34
We need to see why accessing https://www.humanitarianresponse.info/en/operations/colombia gives content in Spanish when the language negotiation is not configured that way.

**Comment by javedyousafzai** [comment] 2015-09-28 09:42
If we keep the same 'Translation settings' for the websties, then we should show all the content regardless of the language they were uploaded. Take [Ukraine] (https://www.humanitarianresponse.info/ru/operations/ukraine) as an example.

**Comment by javedyousafzai** [comment] 2015-09-30 08:41
in our Monday call, we spent sometime discussing how the site translation should actually work to show the content based on the language option selection.

My argument is, regardless the language the audience choose, lets show all the content. This way we show everything, either in Spanish or English. The best example is browsing [Ukraine website in Russian] (https://www.humanitarianresponse.info/ru/operations/ukraine). You can see that content appear in mix language. 

Logically it makes sense that the site should show the content in the 'chosen' language only, but given the limited language capacity of our IMOs, we will hardly have IMO where he/she upload a content and translate in the multiple languages. 

@andrejverity! any comments?

**Comment by andrejverity** [comment] 2015-09-30 08:54
Yes @javedyousafzai is correct. Language option change only affects the navigation, block titles, etc.  (essentially all the framework around the content).  We show all content.

It may seem strange, but this works and is appropriate for our audience.

**Comment by pcambra** [comment] 2015-11-10 10:24
I don't see this happening anymore, we don't seem to filter by language anywhere and I'm thinking this might be a cache issue, could we contact the operations affected by this to see if they have feedback of this still happening? we have included a couple of changes recently that might have mitigated this.

**Comment by emmajane** [comment] 2015-12-31 16:00
Emailed Gabriel 31 December 2015 to confirm if this is still an issue.

**Comment by emmajane** [comment] 2016-01-18 08:02
No reply back from Gabriel. Assuming fixed and closing. Can re-open if needed.

**Closed by emmajane** 2016-01-18 08:02 UTC
Labels: bug
