### ISSUE TITLE
Posting content from external websites via API into HR.info

### ISSUE THREAD

**Issue by javedyousafzai** [humanitarianresponse/site#57] opened 2015-08-19 13:09 UTC
Need to find ways to have the ‘Post’ API where users from other systems e.g. UNHCR can post their assessments to HR.info Assessment registry. Once the content is posted via API, it will be considered as ‘contributed’ content where user will review it, modify the necessary meta-data before it is saved in the platform.

**Comment by emmajane** [comment] 2015-12-03 11:27
Sample data site for integration: http://data.unhcr.org/ (link was in #98).

**Comment by emmajane** [comment] 2015-12-03 11:30
Duplicate of #49. Closing this issue.

**Closed by emmajane** 2015-12-03 11:30 UTC
Labels: enhancement, integration
